ogen = $(Overture)/bin/ogen

grids: rectangle nonRectangle

rectangle:
	$(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=1
	$(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=2
	$(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=4
	$(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=8
	$(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=16
	$(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=32
	$(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=64

nonRectangle:
	$(ogen) -noplot nonRectangle -prefix=nonRect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=1
	$(ogen) -noplot nonRectangle -prefix=nonRect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=2
	$(ogen) -noplot nonRectangle -prefix=nonRect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=4
	$(ogen) -noplot nonRectangle -prefix=nonRect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=8
	$(ogen) -noplot nonRectangle -prefix=nonRect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=16
	$(ogen) -noplot nonRectangle -prefix=nonRect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=32
	$(ogen) -noplot nonRectangle -prefix=nonRect -order=2 -xa=0. -xb=1. -ya=-.5 -yb=0. -periodic=pn -factor=64


