# Makefile for BA tests


# ogen = /home/henshw/Overture.g/bin/ogen
ogen = $(Overture)/bin/ogen


# Make a 2D rectangular region 
rectangle:
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -factor=2
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -factor=4
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -factor=8
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -factor=16
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -factor=32
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -factor=2
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -factor=4
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -factor=8
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -factor=16
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -factor=32

rectanglep:
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=p -factor=2
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=p -factor=4
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=p -factor=8
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=p -factor=16
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=p -factor=32
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=p -factor=2
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=p -factor=4
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=p -factor=8
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=p -factor=16
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=p -factor=32

rectanglenp:
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=np -factor=2
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=np -factor=4
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=np -factor=8
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=np -factor=16
	 $(ogen) -noplot rectangleArg -prefix=rect -order=2 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=np -factor=32
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=np -factor=2
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=np -factor=4
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=np -factor=8
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=np -factor=16
	 $(ogen) -noplot rectangleArg -prefix=rect -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-.5 -yb=.5 -periodic=np -factor=32

# square for the domain [-1,1]x[-1,1]
cSquare:
	 $(ogen) -noplot rectangleArg -prefix=cSquaree -order=2 -xa=-1 -xb=1 -ya=-1 -yb=1 -factor=2
	 $(ogen) -noplot rectangleArg -prefix=cSquaree -order=2 -xa=-1 -xb=1 -ya=-1 -yb=1 -factor=4
	 $(ogen) -noplot rectangleArg -prefix=cSquaree -order=2 -xa=-1 -xb=1 -ya=-1 -yb=1 -factor=8
	 $(ogen) -noplot rectangleArg -prefix=cSquaree -order=2 -xa=-1 -xb=1 -ya=-1 -yb=1 -factor=16
	 $(ogen) -noplot rectangleArg -prefix=cSquaree -order=2 -xa=-1 -xb=1 -ya=-1 -yb=1 -factor=32
	 $(ogen) -noplot rectangleArg -prefix=cSquaree -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-1 -yb=1 -factor=2
	 $(ogen) -noplot rectangleArg -prefix=cSquaree -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-1 -yb=1 -factor=4
	 $(ogen) -noplot rectangleArg -prefix=cSquaree -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-1 -yb=1 -factor=8
	 $(ogen) -noplot rectangleArg -prefix=cSquaree -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-1 -yb=1 -factor=16
	 $(ogen) -noplot rectangleArg -prefix=cSquaree -numGhost=3 -order=4 -xa=-1 -xb=1 -ya=-1 -yb=1 -factor=32

# small square for the domain [-.5,.5]^2
cSquareSmall:
	 $(ogen) -noplot rectangleArg -prefix=cSquareSmalle -order=2 -xa=-.5 -xb=.5 -ya=-.5 -yb=.5 -factor=2
	 $(ogen) -noplot rectangleArg -prefix=cSquareSmalle -order=2 -xa=-.5 -xb=.5 -ya=-.5 -yb=.5 -factor=4
	 $(ogen) -noplot rectangleArg -prefix=cSquareSmalle -order=2 -xa=-.5 -xb=.5 -ya=-.5 -yb=.5 -factor=8
	 $(ogen) -noplot rectangleArg -prefix=cSquareSmalle -order=2 -xa=-.5 -xb=.5 -ya=-.5 -yb=.5 -factor=16
	 $(ogen) -noplot rectangleArg -prefix=cSquareSmalle -order=2 -xa=-.5 -xb=.5 -ya=-.5 -yb=.5 -factor=32
	 $(ogen) -noplot rectangleArg -prefix=cSquareSmalle -numGhost=3 -order=4 -xa=-.5 -xb=.5 -ya=-.5 -yb=.5 -factor=2
	 $(ogen) -noplot rectangleArg -prefix=cSquareSmalle -numGhost=3 -order=4 -xa=-.5 -xb=.5 -ya=-.5 -yb=.5 -factor=4
	 $(ogen) -noplot rectangleArg -prefix=cSquareSmalle -numGhost=3 -order=4 -xa=-.5 -xb=.5 -ya=-.5 -yb=.5 -factor=8
	 $(ogen) -noplot rectangleArg -prefix=cSquareSmalle -numGhost=3 -order=4 -xa=-.5 -xb=.5 -ya=-.5 -yb=.5 -factor=16
	 $(ogen) -noplot rectangleArg -prefix=cSquareSmalle -numGhost=3 -order=4 -xa=-.5 -xb=.5 -ya=-.5 -yb=.5 -factor=32
# big square for the domain [4,4]^2
cSquareBig:
	 $(ogen) -noplot rectangleArg -prefix=cSquareBige -order=2 -xa=-4 -xb=4 -ya=-4 -yb=4 -factor=2
	 $(ogen) -noplot rectangleArg -prefix=cSquareBige -order=2 -xa=-4 -xb=4 -ya=-4 -yb=4 -factor=4
	 $(ogen) -noplot rectangleArg -prefix=cSquareBige -order=2 -xa=-4 -xb=4 -ya=-4 -yb=4 -factor=8
	 $(ogen) -noplot rectangleArg -prefix=cSquareBige -order=2 -xa=-4 -xb=4 -ya=-4 -yb=4 -factor=16
	 $(ogen) -noplot rectangleArg -prefix=cSquareBige -order=2 -xa=-4 -xb=4 -ya=-4 -yb=4 -factor=32
	 $(ogen) -noplot rectangleArg -prefix=cSquareBige -numGhost=3 -order=4 -xa=-4 -xb=4 -ya=-4 -yb=4 -factor=2
	 $(ogen) -noplot rectangleArg -prefix=cSquareBige -numGhost=3 -order=4 -xa=-4 -xb=4 -ya=-4 -yb=4 -factor=4
	 $(ogen) -noplot rectangleArg -prefix=cSquareBige -numGhost=3 -order=4 -xa=-4 -xb=4 -ya=-4 -yb=4 -factor=8
	 $(ogen) -noplot rectangleArg -prefix=cSquareBige -numGhost=3 -order=4 -xa=-4 -xb=4 -ya=-4 -yb=4 -factor=16
	 $(ogen) -noplot rectangleArg -prefix=cSquareBige -numGhost=3 -order=4 -xa=-4 -xb=4 -ya=-4 -yb=4 -factor=32


# Make a 3D rectangular region for an interface problem
box3d:
	$(ogen) -noplot boxArg -prefix=box3de -xa=-1 -xb=1 -ya=-.5 -yb=.5 -za=-.5 -zb=.5 -order=2 -factor=1 
	$(ogen) -noplot boxArg -prefix=box3de -xa=-1 -xb=1 -ya=-.5 -yb=.5 -za=-.5 -zb=.5 -order=2 -factor=2 
	$(ogen) -noplot boxArg -prefix=box3de -xa=-1 -xb=1 -ya=-.5 -yb=.5 -za=-.5 -zb=.5 -order=2 -factor=4 
	$(ogen) -noplot boxArg -prefix=box3de -xa=-1 -xb=1 -ya=-.5 -yb=.5 -za=-.5 -zb=.5 -order=2 -factor=8 
	$(ogen) -noplot boxArg -prefix=box3de -xa=-1 -xb=1 -ya=-.5 -yb=.5 -za=-.5 -zb=.5 -order=2 -factor=16
	$(ogen) -noplot boxArg -prefix=box3de -xa=-1 -xb=1 -ya=-.5 -yb=.5 -za=-.5 -zb=.5 -numGhost=3 -order=4 -factor=1 
	$(ogen) -noplot boxArg -prefix=box3de -xa=-1 -xb=1 -ya=-.5 -yb=.5 -za=-.5 -zb=.5 -numGhost=3 -order=4 -factor=2 
	$(ogen) -noplot boxArg -prefix=box3de -xa=-1 -xb=1 -ya=-.5 -yb=.5 -za=-.5 -zb=.5 -numGhost=3 -order=4 -factor=4 
	$(ogen) -noplot boxArg -prefix=box3de -xa=-1 -xb=1 -ya=-.5 -yb=.5 -za=-.5 -zb=.5  -numGhost=3-order=4 -factor=8 
	$(ogen) -noplot boxArg -prefix=box3de -xa=-1 -xb=1 -ya=-.5 -yb=.5 -za=-.5 -zb=.5 -numGhost=3 -order=4 -factor=16


# for BA scattering from a sphere 
cbox:
	$(ogen) -noplot boxArg -prefix=cboxe -xa=-2 -xb=2 -ya=-2 -yb=2 -za=-2 -zb=2 -order=2 -factor=1 
	$(ogen) -noplot boxArg -prefix=cboxe -xa=-2 -xb=2 -ya=-2 -yb=2 -za=-2 -zb=2 -order=2 -factor=2 
	$(ogen) -noplot boxArg -prefix=cboxe -xa=-2 -xb=2 -ya=-2 -yb=2 -za=-2 -zb=2 -order=2 -factor=4 
	$(ogen) -noplot boxArg -prefix=cboxe -xa=-2 -xb=2 -ya=-2 -yb=2 -za=-2 -zb=2 -order=2 -factor=8 
	$(ogen) -noplot boxArg -prefix=cboxe -xa=-2 -xb=2 -ya=-2 -yb=2 -za=-2 -zb=2 -order=2 -factor=16
	$(ogen) -noplot boxArg -prefix=cboxe -xa=-2 -xb=2 -ya=-2 -yb=2 -za=-2 -zb=2 -numGhost=3 -order=4 -factor=1 
	$(ogen) -noplot boxArg -prefix=cboxe -xa=-2 -xb=2 -ya=-2 -yb=2 -za=-2 -zb=2 -numGhost=3 -order=4 -factor=2 
	$(ogen) -noplot boxArg -prefix=cboxe -xa=-2 -xb=2 -ya=-2 -yb=2 -za=-2 -zb=2 -numGhost=3 -order=4 -factor=4 
	$(ogen) -noplot boxArg -prefix=cboxe -xa=-2 -xb=2 -ya=-2 -yb=2 -za=-2 -zb=2 -numGhost=3 -order=4 -factor=8 
	$(ogen) -noplot boxArg -prefix=cboxe -xa=-2 -xb=2 -ya=-2 -yb=2 -za=-2 -zb=2 -numGhost=3 -order=4 -factor=16
