# Makefile for Oges and BoundarySolver documentation


# Boundary and interface equation solver 
boundarySolver:
	pdflatex boundarySolver




clean: 
	-rm -f *.aux *.bbl *.blg *.ind *.ilg *.log *.idx *.toc

