// File generated by Dropbox/DARPA/RPI/adePapers/adegdmi/dispersivePlaneWaveInterface3d.maple
real t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21,t22,t23,t24,t25,t26,t27,t28,t29,t30,t31,t32,t33,t34,t35,t36,t37,t38,t39,t40,t41,t42,t43,t44,t45,t46,t47,t48,t49,t50,t51,t52,t53,t54,t55,t56,t57,t58,t59,t60,t61,t62,t63,t64,t65,t66,t67,t68,t69,t70,t71,t72,t73,t74,t75,t76,t77,t78,t79,t80,t81,t82,t83,t84,t85,t86,t87,t88,t89,t90,t91,t92,t93,t94,t95,t96,t97,t98,t99,t100,t101,t102,t103,t104,t105,t106,t107,t108,t109,t110,t111,t112,t113,t114,t115,t116,t117,t118,t119,t120,t121,t122,t123,t124,t125,t126,t127,t128,t129,t130,t131,t132,t133,t134,t135,t136,t137,t138,t139,t140,t141,t142,t143,t144,t145,t146,t147,t148,t149,t150;
// -------------------------------------------------------------------------
// Need: 
//    s=sr + I*si : complex frequency
//    [ax,ay,az] = amplitude vector of incident wave, ax=axr+I*axi etc.
//    [arx,ary,arz] = amplitude vector of reflected wave, arx=arxr+I*arxi etc.
//    [atx,aty,atz] = amplitude vector of transmitted wave, atx=atxr+I*atxi etc.
//    [kx,ky,kz] = incident wave vector, kx=kxr+I*kxi etc. 
//    [krx,kry,krz] = reflected wave vector, krx=krxr+I*krxi etc. 
//    [ktx,kty,ktz] = reflected wave vector, ktx=ktxr+I*ktxi etc. 
// -------------------------------------------------------------------------
// Evaluated:                                                               
//    [Exr,Exi] ,[Eyr,Eyi], [Ezr,Ezi]        : left state                   
//    [Etxr,Etxi] ,[Etyr,Etyi], [Etzr,Etzi]  : right state                  
// -------------------------------------------------------------------------
real Exr,Eyr,Ezr, Exi,Eyi,Ezi;
real Etxr,Etyr,Etzr, Etxi,Etyi,Etzi;
t5 = exp(-kxi * x - y * kyi - z * kzi);
t6 = axr * t5;
t10 = x * kxr + y * kyr + z * kzr;
t11 = cos(t10);
t13 = axi * t5;
t14 = sin(t10);
t20 = exp(-x * krxi - y * kryi - z * krzi);
t21 = arxr * t20;
t25 = x * krxr + y * kryr + z * krzr;
t26 = cos(t25);
t28 = arxi * t20;
t29 = sin(t25);
Exr = t6 * t11 - t13 * t14 + t21 * t26 - t28 * t29;
t31 = ayr * t5;
t33 = ayi * t5;
t35 = aryr * t20;
t37 = aryi * t20;
Eyr = t31 * t11 - t33 * t14 + t35 * t26 - t37 * t29;
t39 = azr * t5;
t41 = azi * t5;
t43 = arzr * t20;
t45 = arzi * t20;
Ezr = t39 * t11 - t41 * t14 + t43 * t26 - t45 * t29;
Exi = t13 * t11 + t6 * t14 + t21 * t29 + t28 * t26;
Eyi = t33 * t11 + t31 * t14 + t37 * t26 + t35 * t29;
Ezi = t41 * t11 + t39 * t14 + t45 * t26 + t43 * t29;
t63 = exp(-x * ktxi - y * ktyi - z * ktzi);
t64 = atxr * t63;
t68 = x * ktxr + y * ktyr + z * ktzr;
t69 = cos(t68);
t71 = atxi * t63;
t72 = sin(t68);
Etxr = t64 * t69 - t71 * t72;
t74 = atyr * t63;
t76 = atyi * t63;
Etyr = t74 * t69 - t76 * t72;
t78 = atzr * t63;
t80 = atzi * t63;
Etzr = t78 * t69 - t80 * t72;
Etxi = t64 * t72 + t71 * t69;
Etyi = t76 * t69 + t74 * t72;
Etzi = t80 * t69 + t78 * t72;

